config/routes.rb
Rails.application.routes.draw do
  #post "/productos" => "productos#create"
  #get "productos/new" => "productos#new"
  #get "productos/:id/delete" => "productos#delete"
  #delete "/productos/:id" => "productos#delete", as: :producto
  resources :productos, only: [:new, :create, :destroy]
  get "/productos/buscar" => "productos#buscar", as: :buscar_producto
  root "productos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/producto.rb
class Producto < ApplicationRecord
	validates :cantidad, presence: true
	validates :nombre, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
	def index
		@productos_por_nombre = Producto.order(:nombre).limit 10
		@productos_por_precio = Producto.order(:precio).limit 3
	end

	def new
		@producto = Producto.new
	end

	def buscar
		#productos_a_buscar = "%#{params[:nombre]}%"
		@nombre_a_buscar = params[:nombre]
		@productos = Producto.where "nombre like ?", "%#{@nombre_a_buscar}%"
	end

	def create
		#valores = params.require(:producto).permit! 03/10/2018
		
		#La seguridad es importante

		valores = params.require(:producto).permit :nombre, :precio, :descripcion, :cantidad
		@producto = Producto.new valores
		if @producto.save
			flash[:notice] = "Producto grabado correctamente"
			redirect_to root_url
		else
			render :new
		end

		#nombre = params["nombre"]
		#descripcion = params["descripcion"]
		#cantidad = params["cantidad"]
		#precio = params["precio"]
		#puts nombre
		#puts descripcion
		#puts cantidad
		#puts precios
	end

	def destroy
		id = params[:id]
		Producto.destroy id
		redirect_to root_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super Camisetas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= nav_bar brand: "Super Camisetas", brand_link: root_url do%>
    <%= form_tag buscar_producto_path, method: :get, class: "navbar-form navbar-right" do %>
      <div class="form-group">
        <%= text_field_tag :nombre, @nombre_a_buscar, class: "form-control" %>
        <%= button_to "Buscar", nil, class: "btn btn-default" %>
      </div>
    <% end %>
  <% end %>
	
	<div class="container">
	    <%= yield %>
	</div>
  </body>
</html>

app/views/productos/buscar.html.erb
<table class="table table-bordered">
	<thead class="thead-dark">
		<tr>
			<th scope="col">Nombre</th>
			<th scope="col">Descripcion</th>
			<th scope="col">Precio</th>
			<th scope="col">Cantidad</th>
			<th scope="col">Opciones</th>
		</tr>
	</thead>
	<tbody>
		<!--<% todos = Producto.order :nombre %>-->
		<% @productos.each do |producto| %>
		<tr>
			<td><%= producto.nombre %></td>
			<td><%= producto.descripcion %></td>
			<td><%= producto.precio %></td>
			<td><%= producto.cantidad %></td>
			<!--<td><a href="/productos/<%= producto.id %>/delete">Delete</a></td>-->
			<td>
				<!--<%= link_to "Delete", producto, method: :delete %>-->
				<%= button_to "Delete", producto, 
										method: :delete,
										class: "btn btn-danger",
										data: { confirm: "Estas seguro que deseas borrar #{producto.nombre}?"}
										 %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/productos/create.html.erb
<html>
Creado!
</html>

app/views/productos/index.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered">
	<thead class="thead-dark">
		<tr>
			<th scope="col">Nombre</th>
			<th scope="col">Descripcion</th>
			<th scope="col">Precio</th>
			<th scope="col">Cantidad</th>
			<th scope="col">Opciones</th>
		</tr>
	</thead>
	<tbody>
		<!--<% todos = Producto.order :nombre %>-->
		<% @productos_por_nombre.each do |producto| %>
		<tr>
			<td><%= producto.nombre %></td>
			<td><%= producto.descripcion %></td>
			<td><%= producto.precio %></td>
			<td><%= producto.cantidad %></td>
			<!--<td><a href="/productos/<%= producto.id %>/delete">Delete</a></td>-->
			<td>
				<!--<%= link_to "Delete", producto, method: :delete %>-->
				<%= button_to "Delete", producto, 
										method: :delete,
										class: "btn btn-danger",
										data: { confirm: "Estas seguro que deseas borrar #{producto.nombre}?"}
										 %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Crear un nuevo producto", new_producto_path %>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Descripcion</th>
			<th>Precio</th>
			<th>Cantidad</th>
			<th>Opciones</th>
		</tr>
	</thead>
	<tbody>
		<!-- Esto es un comentario -->
		<% @productos_por_precio.each do |producto| %>
		<tr>
			<td><%= producto.nombre %></td>
			<td><%= producto.descripcion %></td>
			<td><%= producto.precio %></td>
			<td><%= producto.cantidad %></td>
			<td>
				<!--<%= link_to "Delete", producto, method: :delete %>-->
				<%= button_to "Delete", producto, 
										method: :delete,
										class: "btn btn-danger",
										data: { confirm: "Estas seguro que deseas borrar #{producto.nombre}?"}
										 %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Crear un nuevo producto", new_producto_path %>

app/views/productos/new.html.erb
<% @producto.errors.full_messages.each do |message| %>
	<div class="alert alert-danger" role="alert"><%= message %></div>
<% end %>

<%= form_for @producto do |f| %>

<div class="form-group">
	<%= f.label :nombre %>
	<%= f.text_field :nombre, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :descripcion %>
	<%= f.text_area :descripcion, class: "form-control", rows: 4 %>
</div>

<div class="form-inline">
	<div class="form-group">
		<%= f.label :cantidad %>
		<%= f.number_field :cantidad, step: 1, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :precio %>
		<%= f.number_field :precio, class: "form-control"%>
	</div>

	<%= f.submit "Crear Producto", class: "btn btn-primary" %>

</div>
<% end %>

app/views/productos/new2.html.erb
<!DOCTYPE html>
<html>
<body>
<form role="form" class="form-horizontal">
  <div class="form-group">
    <label for="nombre" class="col-sm-2 control-label">Nombre</label>
    <div class="col-sm-10">
      <input type="text" id="nombre" name="nombre" class="form-control" />
    </div>
  </div><br>
  <div class="form-group">
    <label for="descripcion" class="col-sm-2 control-label">Descripcion</label>
    <div class="col-sm-10">
      <textarea id="descripcion" name="descripcion" class="form-control"> </textarea>
    </div>
  </div><br>
  <div class="form-group">
    <label for="cantidad" class="col-sm-2 control-label">Cantidad</label>
    <div class="col-sm-10">
      <input type="number" id="cantidad" name="cantidad" class="form-control" />
    </div>
  </div><br>
  <div class="form-group">
    <label for="precio" class="col-sm-2 control-label">Precio</label>
    <div class="col-sm-10">
      <input type="number" id="precio" name="precio" step="0.01" class="form-control" />
    </div>
  </div><br>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <input type="submit" value="Crear" />
    </div>
  </div>
</form>
</body>
</html>